# -*- coding: utf-8 -*-
"""作業2 - 計算文字出現次數與頻率.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9dJ_6gIBVK7zV8_npK7atfDgWuMwEDI
"""

import matplotlib.pyplot as plt

file = open('hw2_data.txt',"r")
numdict = {}
for i in file:
  if i in numdict:
    numdict[i]+=1
  else:
    numdict[i]=1

sortednumdict = dict(sorted(numdict.items(), key=lambda item: item[1], reverse=True))

print(f"{len(sortednumdict)}種")

for i in sortednumdict:
  print(f"{i}:{sortednumdict[i]}次")


x = sortednumdict.keys()
h = sortednumdict.values()
plt.bar(x,h)
plt.xlabel('Category')
plt.ylabel('Times')
plt.show()